# 模式 dev/release
env  = "dev"

# 绑定地址
addr = ":8080"  # 绑定地址

# 日志等级
log  = ""

# 定时推送全量节点，单位秒
timer = 3600

# 是否仅启动配置中心接口
only_cc = false

# redis 配置中心缓存配置，可配置多个
[[redis]]
addr     = "127.0.0.1:6379"
password = ""
pool     = 10  # redis连接池大小

# 数据库配置，如果仅启动配置中心，而且使用Redis，无需该配置
[db]
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
dbname   = "gobui"
charset  = "utf8mb4"
pool_max_open = 100
pool_max_idle = 50
pool_max_life = 600