# 模式 dev/release
env  = "dev"

# 绑定地址
addr = ":8080"  # 绑定地址

# 服务端是否处理跨域header 如果您的前端Nginx处理 无需该操作
header = true

# 您的网络环境是否仅支持GET、POST方法
only_gp = false

# 日志等级
log  = ""

# 定时推送全量节点，单位秒
timer = 3600

# 是否仅启动配置中心Api接口
only_cc = false

# redis 配置中心缓存配置，可配置多个
[[redis]]
addr     = "127.0.0.1:16389"
password = ""
pool     = 5  # redis连接池大小

# 数据库配置
[db]
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
dbname   = "mrng"
charset  = "utf8mb4"
pool_max_open = 100
pool_max_idle = 50
pool_max_life = 600